In [5]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"khadijahpatience","key":"09983b76f41ed913049f60fd37b6f995"}'}

In [6]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [7]:
!kaggle competitions list

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
ref                                                                           deadline             category         reward  teamCount  userHasEntered
----------------------------------------------------------------------------  -------------------  --------  -------------  ---------  --------------
https://www.kaggle.com/competitions/passenger-screening-algorithm-challenge   2017-12-15 23:59:00  Featured  1,500,000 Usd        518           False
https://www.kaggle.com/competitions/zillow-prize-1                            2018-01-10 15:59:00  Featured  1,200,000 Usd       3770           False
https://www.kaggle.com/competitions/data-science-bowl-2017                    2017-04-12 23:59:00  Featured  1,000,000 Usd       1972           False
https://www.kaggle.com/competitions/vesuvius-challenge-ink-detection          2023-06-14 23:59:00  Featured  1,000,000 Usd       1249           False
https://www.kaggle.com/competitions/arc-prize-2026-arc-agi-3                  2026-11-02 23:59:00  Featured    850,000 Usd       1445           False
https://www.kaggle.com/competitions/arc-prize-2026-arc-agi-2                  2026-11-02 23:59:00  Featured    700,000 Usd        971           False
https://www.kaggle.com/competitions/gemini-3                                  2025-12-12 23:59:00  Featured    500,000 Usd       4090           False
https://www.kaggle.com/competitions/openai-gpt-oss-20b-red-teaming            2025-08-26 23:59:00  Featured    500,000 Usd        602           False
https://www.kaggle.com/competitions/openai-to-z-challenge                     2025-06-29 23:59:00  Featured    500,000 Usd        225           False
https://www.kaggle.com/competitions/arc-prize-2026-paper-track                2026-11-09 23:59:00  Featured    450,000 Usd         77           False
https://www.kaggle.com/competitions/pokemon-tcg-ai-battle-challenge-strategy  2026-09-13 23:59:00  Featured    240,000 Usd         97           False
https://www.kaggle.com/competitions/llm-prompt-recovery                       2024-04-16 23:59:00  Featured    200,000 Usd       2175           False
https://www.kaggle.com/competitions/vesuvius-challenge-surface-detection      2026-02-27 23:59:00  Research    200,000 Usd       1391           False
https://www.kaggle.com/competitions/asl-fingerspelling                        2023-08-24 23:59:00  Research    200,000 Usd       1314           False
https://www.kaggle.com/competitions/second-annual-data-science-bowl           2016-03-14 23:59:00  Featured    200,000 Usd        192           False
https://www.kaggle.com/competitions/gemma-4-good-hackathon                    2026-05-18 23:59:00  Featured    200,000 Usd       1611           False
https://www.kaggle.com/competitions/kaggle-measuring-agi                      2026-04-16 23:59:00  Featured    200,000 Usd       1068           False
https://www.kaggle.com/competitions/datasciencebowl                           2015-03-16 23:59:00  Featured    175,000 Usd       1049           False
https://www.kaggle.com/competitions/data-science-bowl-2019                    2020-01-22 23:59:00  Featured    160,000 Usd       3493           False
https://www.kaggle.com/competitions/feedback-prize-2021                       2022-03-15 23:59:00  Featured    160,000 Usd       2058           False

In [8]:
!kaggle competitions download -c learn-ai-bbc

Downloading learn-ai-bbc.zip to /content
100% 1.85M/1.85M [00:01<00:00, 1.81MB/s]

In [9]:
!unzip -o learn-ai-bbc.zip
!ls -la

Archive:  learn-ai-bbc.zip
  inflating: BBC News Sample Solution.csv
  inflating: BBC News Test.csv
  inflating: BBC News Train.csv
total 6876
drwxr-xr-x 1 root root    4096 Jun 26 16:51  .
drwxr-xr-x 1 root root    4096 Jun 26 16:36  ..
-rw-r--r-- 1 root root   10369 Dec  2  2019 'BBC News Sample Solution.csv'
-rw-r--r-- 1 root root 1712432 Dec  2  2019 'BBC News Test.csv'
-rw-r--r-- 1 root root 3351206 Dec  2  2019 'BBC News Train.csv'
drwxr-xr-x 4 root root    4096 Jun  4 13:32  .config
-rw-r--r-- 1 root root      72 Jun 26 16:51  kaggle.json
-rw-r--r-- 1 root root 1936538 Dec  2  2019  learn-ai-bbc.zip
drwxr-xr-x 1 root root    4096 Jun  4 13:32  sample_data

In [10]:
import pandas as pd
import os

print("Available CSV files:")
for file in os.listdir('.'):
    if file.endswith('.csv'):
        print(" -", file)

Available CSV files:
 - BBC News Train.csv
 - BBC News Test.csv
 - BBC News Sample Solution.csv

In [11]:
df = pd.read_csv("BBC News Train.csv")
df.head()

   ArticleId                                               Text  Category
0       1833  worldcom ex-boss launches defence lawyers defe...  business
1        154  german business confidence slides german busin...  business
2       1101  bbc poll indicates economic gloom citizens in ...  business
3       1976  lifestyle  governs mobile choice  faster  bett...      tech
4        917  enron bosses in $168m payout eighteen former e...  business

In [12]:
!kaggle competitions list

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
ref                                                                           deadline             category         reward  teamCount  userHasEntered
----------------------------------------------------------------------------  -------------------  --------  -------------  ---------  --------------
https://www.kaggle.com/competitions/passenger-screening-algorithm-challenge   2017-12-15 23:59:00  Featured  1,500,000 Usd        518           False
https://www.kaggle.com/competitions/zillow-prize-1                            2018-01-10 15:59:00  Featured  1,200,000 Usd       3770           False
https://www.kaggle.com/competitions/data-science-bowl-2017                    2017-04-12 23:59:00  Featured  1,000,000 Usd       1972           False
https://www.kaggle.com/competitions/vesuvius-challenge-ink-detection          2023-06-14 23:59:00  Featured  1,000,000 Usd       1249           False
https://www.kaggle.com/competitions/arc-prize-2026-arc-agi-3                  2026-11-02 23:59:00  Featured    850,000 Usd       1445           False
https://www.kaggle.com/competitions/arc-prize-2026-arc-agi-2                  2026-11-02 23:59:00  Featured    700,000 Usd        971           False
https://www.kaggle.com/competitions/gemini-3                                  2025-12-12 23:59:00  Featured    500,000 Usd       4090           False
https://www.kaggle.com/competitions/openai-gpt-oss-20b-red-teaming            2025-08-26 23:59:00  Featured    500,000 Usd        602           False
https://www.kaggle.com/competitions/openai-to-z-challenge                     2025-06-29 23:59:00  Featured    500,000 Usd        225           False
https://www.kaggle.com/competitions/arc-prize-2026-paper-track                2026-11-09 23:59:00  Featured    450,000 Usd         77           False
https://www.kaggle.com/competitions/pokemon-tcg-ai-battle-challenge-strategy  2026-09-13 23:59:00  Featured    240,000 Usd         97           False
https://www.kaggle.com/competitions/llm-prompt-recovery                       2024-04-16 23:59:00  Featured    200,000 Usd       2175           False
https://www.kaggle.com/competitions/vesuvius-challenge-surface-detection      2026-02-27 23:59:00  Research    200,000 Usd       1391           False
https://www.kaggle.com/competitions/asl-fingerspelling                        2023-08-24 23:59:00  Research    200,000 Usd       1314           False
https://www.kaggle.com/competitions/second-annual-data-science-bowl           2016-03-14 23:59:00  Featured    200,000 Usd        192           False
https://www.kaggle.com/competitions/gemma-4-good-hackathon                    2026-05-18 23:59:00  Featured    200,000 Usd       1611           False
https://www.kaggle.com/competitions/kaggle-measuring-agi                      2026-04-16 23:59:00  Featured    200,000 Usd       1068           False
https://www.kaggle.com/competitions/datasciencebowl                           2015-03-16 23:59:00  Featured    175,000 Usd       1049           False
https://www.kaggle.com/competitions/data-science-bowl-2019                    2020-01-22 23:59:00  Featured    160,000 Usd       3493           False
https://www.kaggle.com/competitions/feedback-prize-2021                       2022-03-15 23:59:00  Featured    160,000 Usd       2058           False

In [22]:
!kaggle competitions download -c learn-ai-bbc
!unzip learn-ai-bbc.zip
!ls -la

learn-ai-bbc.zip: Skipping, found more recently modified local copy (use --force to force download)
Archive:  learn-ai-bbc.zip
replace BBC News Sample Solution.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: total 10148
drwxr-xr-x 1 root root    4096 Jun 26 16:53  .
drwxr-xr-x 1 root root    4096 Jun 26 16:36  ..
-rw-r--r-- 1 root root   10369 Dec  2  2019 'BBC News Sample Solution.csv'
-rw-r--r-- 1 root root 1712432 Dec  2  2019 'BBC News Test.csv'
-rw-r--r-- 1 root root 3351206 Dec  2  2019 'BBC News Train.csv'
drwxr-xr-x 4 root root    4096 Jun  4 13:32  .config
-rw-r--r-- 1 root root      72 Jun 26 16:51  kaggle.json
-rw-r--r-- 1 root root 1936538 Dec  2  2019  learn-ai-bbc.zip
-rw-r--r-- 1 root root 3349718 Jun 26 16:53  newsbot_dataset.csv
drwxr-xr-x 1 root root    4096 Jun  4 13:32  sample_data

In [14]:
import pandas as pd
df = pd.read_csv("BBC News Train.csv")
df.head()

   ArticleId                                               Text  Category
0       1833  worldcom ex-boss launches defence lawyers defe...  business
1        154  german business confidence slides german busin...  business
2       1101  bbc poll indicates economic gloom citizens in ...  business
3       1976  lifestyle  governs mobile choice  faster  bett...      tech
4        917  enron bosses in $168m payout eighteen former e...  business

In [15]:
import pandas as pd

df = pd.read_csv("BBC News Train.csv")
df.head()

   ArticleId                                               Text  Category
0       1833  worldcom ex-boss launches defence lawyers defe...  business
1        154  german business confidence slides german busin...  business
2       1101  bbc poll indicates economic gloom citizens in ...  business
3       1976  lifestyle  governs mobile choice  faster  bett...      tech
4        917  enron bosses in $168m payout eighteen former e...  business

In [16]:
len(df)

1490

In [17]:
df['Category'].value_counts()

Category
sport            346
business         336
politics         274
entertainment    273
tech             261
Name: count, dtype: int64

In [18]:
df.columns

Index(['ArticleId', 'Text', 'Category'], dtype='object')

In [19]:
text_column = 'text'

In [20]:
text_column = 'content'

In [21]:
import pandas as pd
import numpy as np

# 1. Examine your dataset
print("Dataset Info:")
print(f"Shape: {df.shape}")
print(f"Columns: {df.columns.tolist()}")
print("\nFirst few rows:")
print(df.head())

# 2. Identify text and category columns
# UPDATE this based on your dataset
text_column = 'Text'   # changed from 'content' to 'Text'
category_column = 'Category' # changed from 'category' to 'Category'

# 3. Check for missing values
print("\nMissing values:")
print(df.isnull().sum())

# 4. Remove rows with missing text or categories
df_clean = df.dropna(subset=[text_column, category_column])

# 5. Check category distribution
print("\nCategory distribution:")
print(df_clean[category_column].value_counts())

# 6. Sample if dataset is too large (keep under 2000 for Colab)
if len(df_clean) > 2000:
    df_final = df_clean.sample(n=2000, random_state=42)
    print(f"\nSampled dataset to {len(df_final)} rows")
else:
    df_final = df_clean

# 7. Rename columns for consistency
df_final = df_final.rename(columns={
    text_column: 'content',
    category_column: 'category'
})

# 8. Save prepared dataset
df_final.to_csv('newsbot_dataset.csv', index=False)
print("\n✅ Dataset prepared and saved as 'newsbot_dataset.csv'")

Dataset Info:
Shape: (1490, 3)
Columns: ['ArticleId', 'Text', 'Category']

First few rows:
   ArticleId                                               Text  Category
0       1833  worldcom ex-boss launches defence lawyers defe...  business
1        154  german business confidence slides german busin...  business
2       1101  bbc poll indicates economic gloom citizens in ...  business
3       1976  lifestyle  governs mobile choice  faster  bett...      tech
4        917  enron bosses in $168m payout eighteen former e...  business

Missing values:
ArticleId    0
Text         0
Category     0
dtype: int64

Category distribution:
Category
sport            346
business         336
politics         274
entertainment    273
tech             261
Name: count, dtype: int64

✅ Dataset prepared and saved as 'newsbot_dataset.csv'